### Урок 4.4: дополнительные концепции `NumPy`

In [1]:
import numpy as np

### Вычисления

Создадим массив `M` из последовательности чисел (вспомним про `arange()`):

In [2]:
M = np.arange(1, 10, 0.003)
M

array([1.   , 1.003, 1.006, ..., 9.991, 9.994, 9.997])

Округление:

In [3]:
np.round(M)  # до целого

array([ 1.,  1.,  1., ..., 10., 10., 10.])

In [4]:
np.round(M, 1)  # до 1го знака 

array([ 1.,  1.,  1., ..., 10., 10., 10.])

In [13]:
np.round(M, 2)

array([ 1.  ,  1.  ,  1.01, ...,  9.99,  9.99, 10.  ])

In [ ]:
n

Возьмём массив поинтереснее с точки зрения округления:

In [6]:
A = np.array([2.5, 2.7, 8.1, 9.25])
A

array([2.5 , 2.7 , 8.1 , 9.25])

In [7]:
np.floor(A)  # в меньшую сторону

array([2., 2., 8., 9.])

In [8]:
np.ceil(A)  # в большую сторону

array([ 3.,  3.,  9., 10.])

Добавим ко всем элементам `A` 2:

In [9]:
np.add(A, 2)

array([ 4.5 ,  4.7 , 10.1 , 11.25])

In [14]:
A + 2 

array([ 4.5 ,  4.7 , 10.1 , 11.25])

А теперь вычтем 1:

In [20]:
np.subtract(A, 1)

array([1.5 , 1.7 , 7.1 , 8.25])

Суммируем все значения:

In [15]:
np.sum(A)

22.55

In [16]:
A.sum()

22.55

Или найдём их произведения:

In [17]:
np.prod(A)

505.74375

In [18]:
A.prod()

505.74375

### Объекты `Datetimes` 

Попробуем сравнить две даты, сохранённые как строки:

In [43]:
d1 = "2019-02-25"
d2 = "2019-02-28"

Не получилось и это ожидаемо: нельзя из одного текста вычесть другой. Как быть? Превратить строку в специальный объект дата-время, который можно сравнивать с другими датами, считать, сколько времени прошло и так далее. В библиотеке `NumPy` такой объект есть:

In [49]:
start = np.datetime64(d1)

Зададим `finish` и проверим, что теперь даты можно сравнивать и получать разницу в днях (и не только):

In [45]:
finish = np.datetime64(d2)

In [58]:
finish - start

numpy.timedelta64(3,'D')

In [64]:
d3 = start - np.timedelta64(5, 'D')

In [62]:
d3

numpy.datetime64('2019-02-20')

In [32]:
from datetime import datetime

date_str_1 = "2018-01-01"
date_str_2 = "2020-02-08"

date_str_1 = datetime.strptime(date_str_1, "%Y-%m-%d")
date_str_2 = datetime.strptime(date_str_2, "%Y-%m-%d")

In [40]:
date_str_2 - date_str_1

datetime.timedelta(days=768)

In [42]:
from datetime import timedelta

new_date = date_str_1 + timedelta(hours=12, minutes=15, seconds=3)
new_date

datetime.datetime(2018, 1, 1, 12, 15, 3)

In [55]:
date_str = datetime.strftime(new_date, "%Y-%m-%dT%H:%M:%S")
date_str

'2018-01-01T12:15:03'

In [57]:

my_date = datetime.strftime(new_date, "%Y-%m-01")
my_date

'2018-01-01'