# Библиотека `NumPy`: часть 2

*Алла Тамбовцева*

## Домашнее задание 

### Описание домашнего задания и формат сдачи

В домашнем задании необходимо решить предложенные задачи по программированию – вписать свой код в ячейки после условий задач вместо комментария `### YOUR CODE HERE ###` в файле *homework-numpy2.ipynb* и сохранить изменения, используя опцию *Save and Checkpoint* из вкладки меню *File* или кнопку *Save and Checkpoint* на панели инструментов. Итоговый файл в формате `.ipynb` (файл Jupyter Notebook) необходимо загрузить в личный кабинет обучающей онлайн платформы Skillbox (https://go.skillbox.ru/) и отправить на проверку.

### Задание 1
Загрузить из файла `array_hw.npy` массив и сохранить его как `arr`. Массив содержит объёмы продаж мороженого (в штуках) в 5 магазинах за одну неделю в июне (7 дней, с понедельника до воскресенья). В заданиях 2-5 нужно работать с массивом `arr`.

In [1]:
import numpy as np

In [2]:
arr = np.load("array_hw.npy")
arr

array([[100,  80,  70,  60, 120],
       [ 65,  55,  20,  50,  60],
       [ 80,  90,  75,  80,  60],
       [ 45,  60,  70,  20,  40],
       [ 82,  47,  56,  89,  92],
       [115, 120, 113, 106, 107],
       [ 46,  74,  23,  34,  19]], dtype=int64)

### Задание 2
Если думать о массиве `arr` как о таблице, сейчас в таблице магазины идут по столбцам (1 магазин = 1 столбец, всего 5), а дни – по строкам (1 день = 1 строка, всего 7). Преобразовать массив `arr` таким образом, чтобы по строкам шли магазины, а по столбцам – дни (1 строка = 1 магазин). Сохранить изменения. Проверить, что форма массива изменилась.

In [7]:
new_arr = arr.transpose()
new_arr

array([[100,  65,  80,  45,  82, 115,  46],
       [ 80,  55,  90,  60,  47, 120,  74],
       [ 70,  20,  75,  70,  56, 113,  23],
       [ 60,  50,  80,  20,  89, 106,  34],
       [120,  60,  60,  40,  92, 107,  19]], dtype=int64)

### Задание 3

Давайте представим, что информация по продажам обновилась: оказалось, что пятый магазин в воскресенье продал не 19 порций мороженого, а 25, и второй магазин продал во вторник не 55 порций, а 65. Изменить массив `arr` в соответствии с этой информацией.

In [8]:
new_arr[4][6] = 25
new_arr[1][1] = 65
new_arr

array([[100,  65,  80,  45,  82, 115,  46],
       [ 80,  65,  90,  60,  47, 120,  74],
       [ 70,  20,  75,  70,  56, 113,  23],
       [ 60,  50,  80,  20,  89, 106,  34],
       [120,  60,  60,  40,  92, 107,  25]], dtype=int64)

### Задание 4

Посчитать суммарный объём продаж мороженого по всем магазинам.

In [9]:
new_arr.sum(axis=1)

array([533, 536, 427, 439, 504], dtype=int64)

### Задание 5

Выгрузить обновлённый массив `arr` в txt-файл. Сам txt-файл загружать в систему не нужно, только написать соответствующий код в ipynb-файл.

In [12]:
np.savetxt("new_arr.txt", new_arr)

In [13]:
my_arr = np.loadtxt("new_arr.txt")

In [19]:
np.int64(my_arr)

array([[100,  65,  80,  45,  82, 115,  46],
       [ 80,  65,  90,  60,  47, 120,  74],
       [ 70,  20,  75,  70,  56, 113,  23],
       [ 60,  50,  80,  20,  89, 106,  34],
       [120,  60,  60,  40,  92, 107,  25]], dtype=int64)

### Задание 6
Дан массив `income`, содержащий значения прибыли магазина в тысячах на начало, середину и конец года, за четыре года подряд (значения никак не сгруппированы, можно считать, что они так выгрузились из файла). 
Изменить форму массива так, чтобы значения были сгруппированы по три значения в каждом списке внутри массива (прибыль на начало, середину и конец года).

In [20]:
# массив
income = np.array([1000, 2000, 3500, 
                   2500, 1500, 3800, 
                   1200, 9000, 12000,
                   4500, 6700, 11000])

In [22]:
income = income.reshape(4 ,3)
income

array([[ 1000,  2000,  3500],
       [ 2500,  1500,  3800],
       [ 1200,  9000, 12000],
       [ 4500,  6700, 11000]])

### Задание 7
Создать список `turnout` (*list*, не массив), содержащий следующие значения явки на избирательные участки в процентах:

23.56, 45.78, 34.92, 57.34, 56.55, 67.23.

Создать, используя списковые включения и встроенные, не из `NumPy`, функции для округления, новый список `turnout_r`, который состоит из округлённых до первого знака после запятой значений явки из `turnout`.

In [24]:
turnout = [23.56, 45.78, 34.92, 57.34, 56.55, 67.23]

In [25]:
turnout_r = [round(num,1) for num in turnout]

In [26]:
turnout_r

[23.6, 45.8, 34.9, 57.3, 56.5, 67.2]

### Задание 8
Выполнить те же операции, что и в предыдущей задаче, но с использованием массивов и функций `NumPy`. Другими словами, создать массив `turnout` и на его основе создать массив `turnout_r` с округлёнными до первого знака значениями явки.

In [30]:
turnout = np.array([23.56, 45.78, 34.92, 57.34, 56.55, 67.23])

In [31]:
turnout_r = np.round(turnout, 1)

In [32]:
turnout_r

array([23.6, 45.8, 34.9, 57.3, 56.6, 67.2])

### Задание 9

Зайдите на [страницу](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B6%D0%B4%D1%83%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D1%8B%D0%B9_%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81_%D1%81%D1%87%D0%B0%D1%81%D1%82%D1%8C%D1%8F) Википедии, посвящённую Международному индексу счастья, выберите из таблицы **2012 Международный индекс счастья** любые 5 стран и любые 3 показателя и создайте структурированный массив `happy`, такой, в котором есть поле «название страны» и поля для трёх выбранных показателей. Выберите подходящий тип для каждого поля (показателя) в массиве и учтите это при создание структурированного массива. Выведите полученный массив на экран.

In [38]:
happy = np.array([("Коста-Рика", 64.0, 7.3, 79.3, 2.5),
                  ( "Вьетнам", 60.4, 5.8, 75.2, 1.4),
                  ("Колумбия", 59.8, 6.4, 73.7, 1.8),
                  ( "Белиз", 59.3, 6.5, 76.1, 2.1),
                  ( "Сальвадор", 58.9, 6.7, 72.2, 2.0)],
                 dtype=[("country", "U10"),
                        ("hpi", float),
                        ("satisfaction_life", float),
                        ("life_expectancy", float),
                        ("ecological_footprint", float)])

print(happy)

[('Коста-Рика', 64. , 7.3, 79.3, 2.5) ('Вьетнам', 60.4, 5.8, 75.2, 1.4)
 ('Колумбия', 59.8, 6.4, 73.7, 1.8) ('Белиз', 59.3, 6.5, 76.1, 2.1)
 ('Сальвадор', 58.9, 6.7, 72.2, 2. )]


### Задание 10
Сконвертируйте полученный в предыдущей задаче структурированный массив в обычный список и выведите на экран его второй элемент.

In [40]:
happy.tolist()

[('Коста-Рика', 64.0, 7.3, 79.3, 2.5),
 ('Вьетнам', 60.4, 5.8, 75.2, 1.4),
 ('Колумбия', 59.8, 6.4, 73.7, 1.8),
 ('Белиз', 59.3, 6.5, 76.1, 2.1),
 ('Сальвадор', 58.9, 6.7, 72.2, 2.0)]

In [41]:
happy.tolist()[1]

('Вьетнам', 60.4, 5.8, 75.2, 1.4)

In [48]:
happy[1]

('Вьетнам', 60.4, 5.8, 75.2, 1.4)

In [44]:
happy["life_expectancy"]

array([79.3, 75.2, 73.7, 76.1, 72.2])

In [45]:
happy[["country","life_expectancy"]]


array([('Коста-Рика', 79.3), ('Вьетнам', 75.2), ('Колумбия', 73.7),
       ('Белиз', 76.1), ('Сальвадор', 72.2)],
      dtype={'names':['country','life_expectancy'], 'formats':['<U10','<f8'], 'offsets':[0,56], 'itemsize':72})

In [49]:
happy["country"][1]

'Вьетнам'